//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NextPvrWebConsole.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NextPvrWebConsole.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [version] (
        ///	databaseversion			int					NOT NULL	
        ///)
        ///GO
        ///
        ///CREATE TABLE [user] (
        ///	oid						integer				NOT NULL			PRIMARY KEY				AUTOINCREMENT,
        ///	username				varchar(100)		NOT NULL,
        ///	emailaddress			varchar(320)		NOT NULL,
        ///	[passwordhash]			varchar(100)		NOT NULL,
        ///	userrole				integer				NOT NULL,
        ///	datecreatedutc			datetime			NOT NULL,
        ///	lastloggedinutc			datetime			NOT NULL,
        ///	administrator			bit					NOT NULL,
        ///	[readonly]				bit					NOT NULL,	
        ///	defaultrecordingdirectoryoid	integer		NOT N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDatabase_sql {
            get {
                return ResourceManager.GetString("CreateDatabase_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password reset request was made for this account for NextPVR Webconsole.
        ///
        ///If you did not make this request, delete this email.
        ///
        ///If you did make this request and would like to continue, copy the following link into your web browser and follow the instructions.
        ///
        ///{Url}.
        /// </summary>
        internal static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
    }
}
